export const NICHES = {
  friser: {
    id: 'friser',
    label: 'Frisör',
    icon: '✂️',
    primaryColor: '#2d2d2d',
    accentColor: '#e8a0b4',
    bgColor: '#faf8f6',
    textColor: '#1a1a1a',
    fontHeading: "'Cormorant Garamond', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    googleFonts: 'Cormorant+Garamond:wght@400;600;700&family=Inter:wght@300;400;500',
    defaultDark: false,
    defaultPhotos: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1400&q=80&fit=crop',
    ],
    heroTagline: 'Dein Stil. Unser Handwerk.',
    heroSubline: 'Professionelle Haarpflege & Styling in [Stadt]',
    heroCta: 'Termin buchen',
    servicesLabel: 'Leistungen',
    servicesDefault: [
      { name: 'Damenhaarschnitt', price: '45 €', desc: 'Waschen, schneiden, föhnen', duration: 60 },
      { name: 'Herrenhaarschnitt', price: '28 €', desc: 'Waschen, schneiden, föhnen', duration: 45 },
      { name: 'Coloration', price: 'ab 60 €', desc: 'Farbe, Strähnen, Balayage', duration: 90 },
      { name: 'Kinderhaarschnitt', price: '18 €', desc: 'Für Kinder bis 12 Jahre', duration: 30 },
      { name: 'Föhnen & Styling', price: '22 €', desc: 'Waschen, föhnen, stylen', duration: 45 },
      { name: 'Strähnen', price: 'ab 40 €', desc: 'Highlights & Balayage', duration: 90 },
      { name: 'Dauerwelle', price: 'ab 50 €', desc: 'Klassisch oder modern', duration: 90 },
      { name: 'Aufbaubehandlung', price: '30 €', desc: 'Intensive Haarpflege', duration: 30 },
    ],
    extrasCta: 'Jetzt Termin vereinbaren',
    hasMenu: false,
    hasPricelist: true,
    teamLabel: 'Unser Team',
    aboutLabel: 'Über uns',
    aboutDefault: 'Dein Haar liegt uns am Herzen. Mit viel Erfahrung, hochwertigen Produkten und einem Gespür für aktuelle Trends bringen wir deine Wunschfrisur zum Leben.',
    teamDefault: [
      { name: 'Sophie Müller',  role: 'Senior Stylistin',   photoUrl: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=faces' },
      { name: 'Anna Weber',     role: 'Color-Expertin',     photoUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=400&fit=crop&crop=faces' },
      { name: 'Lisa Koch',      role: 'Styling & Beratung', photoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=faces' },
      { name: 'Jana Bauer',     role: 'Haarpflege & Pflege',photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=faces' },
    ],
  },

  barber: {
    id: 'barber',
    label: 'Barber',
    icon: '💈',
    primaryColor: '#1a1a1a',
    accentColor: '#c9a84c',
    bgColor: '#0d0d0d',
    textColor: '#f5f0e8',
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    googleFonts: 'Playfair+Display:wght@400;700;900&family=Inter:wght@300;400;500',
    defaultDark: true,
    defaultPhotos: [
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1512864084360-7c0c4d0a0c8b?w=1400&q=80&fit=crop',
    ],
    heroTagline: 'Wo Stil auf Handwerk trifft',
    heroSubline: 'Premium Haarschnitte & Bartpflege in [Stadt]',
    heroCta: 'Termin buchen',
    servicesLabel: 'Leistungen',
    servicesDefault: [
      { name: 'Haarschnitt', price: '25 €', desc: 'Waschen, schneiden, föhnen', duration: 45 },
      { name: 'Bartrasur', price: '20 €', desc: 'Hot Towel, Rasur, Pflege', duration: 30 },
      { name: 'Haar + Bart', price: '40 €', desc: 'Komplett-Paket mit Styling', duration: 60 },
      { name: 'Kinder bis 12', price: '15 €', desc: 'Haarschnitt für Kinder', duration: 30 },
      { name: 'Kopfrasur', price: '20 €', desc: 'Glattrasur mit Hot Towel', duration: 30 },
      { name: 'Augenbrauen', price: '10 €', desc: 'Formen & Pflegen', duration: 15 },
      { name: 'Färben', price: 'ab 15 €', desc: 'Tönung & Colorierung', duration: 45 },
      { name: 'Royal Shave', price: '35 €', desc: 'Luxus-Rasur mit Massage', duration: 45 },
    ],
    extrasCta: 'Jetzt Termin vereinbaren',
    hasMenu: false,
    hasPricelist: true,
    teamLabel: 'Unser Team',
    aboutLabel: 'Über uns',
    aboutDefault: 'Wir stehen für erstklassige Handwerkskunst und individuelle Beratung. Jeder Besuch ist ein Erlebnis — von der ersten Beratung bis zum perfekten Finish.',
    teamDefault: [
      { name: 'Marco Rossi',  role: 'Head Barber',     photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=faces' },
      { name: 'Kai Fischer',  role: 'Bart-Spezialist', photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=faces' },
      { name: 'Tom Klein',    role: 'Classic Cuts',    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=faces' },
      { name: 'Nico Bräuning',role: 'Fade Specialist', photoUrl: 'https://images.unsplash.com/photo-1500048993953-d23a436266cf?w=400&h=400&fit=crop&crop=faces' },
    ],
  },

  fastfood: {
    id: 'fastfood',
    label: 'Fastfood',
    icon: '🍔',
    primaryColor: '#e63946',
    accentColor: '#f4d03f',
    bgColor: '#1a0a00',
    textColor: '#fff8f0',
    fontHeading: "'Bebas Neue', Impact, sans-serif",
    fontBody: "'Roboto', system-ui, sans-serif",
    googleFonts: 'Bebas+Neue&family=Roboto:wght@300;400;700',
    defaultDark: true,
    defaultPhotos: [
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1550547660-d9450f859349?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1586816001966-79b736744398?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=1400&q=80&fit=crop',
    ],
    heroTagline: 'Frisch. Schnell. Unwiderstehlich.',
    heroSubline: 'Die besten Burger & Snacks in [Stadt]',
    heroCta: 'Jetzt bestellen',
    servicesLabel: 'Unsere Speisekarte',
    servicesDefault: [
      { name: 'Classic Burger', price: '8,90 €', desc: 'Rindfleisch, Cheddar, Salat, Tomate' },
      { name: 'BBQ Burger', price: '10,90 €', desc: 'Doppeltes Fleisch, BBQ-Sauce, Zwiebeln' },
      { name: 'Chicken Crispy', price: '9,50 €', desc: 'Knuspriges Hühnchen, Coleslaw, Mayo' },
      { name: 'Pommes + Drink', price: '4,90 €', desc: 'Große Portion + 0,5l Getränk' },
    ],
    extrasCta: 'Online bestellen',
    hasMenu: true,
    hasPricelist: false,
    teamLabel: 'Unser Team',
    aboutLabel: 'Unsere Geschichte',
    aboutDefault: 'Seit Jahren bringen wir euch die saftigsten Burger und knusprigsten Snacks. Frische Zutaten, eigene Rezepte, echter Geschmack — das ist unser Versprechen.',
  },

  cafe: {
    id: 'cafe',
    label: 'Café',
    icon: '☕',
    primaryColor: '#6f4e37',
    accentColor: '#d4a96a',
    bgColor: '#faf6f0',
    textColor: '#2c1810',
    fontHeading: "'Lora', Georgia, serif",
    fontBody: "'Source Sans 3', system-ui, sans-serif",
    googleFonts: 'Lora:wght@400;600;700&family=Source+Sans+3:wght@300;400;600',
    defaultDark: false,
    defaultPhotos: [
      'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1400&q=80&fit=crop',
    ],
    heroTagline: 'Ein Moment für dich',
    heroSubline: 'Handgefertigter Kaffee & hausgemachte Kuchen in [Stadt]',
    heroCta: 'Tisch reservieren',
    servicesLabel: 'Unsere Karte',
    servicesDefault: [
      { name: 'Espresso', price: '2,50 €', desc: 'Kräftig & aromatisch' },
      { name: 'Cappuccino', price: '3,80 €', desc: 'Perfekter Milchschaum, täglich frisch' },
      { name: 'Avocado Toast', price: '9,50 €', desc: 'Sauerteig, Avocado, Rucola' },
      { name: 'Hausgemachter Kuchen', price: '4,50 €', desc: 'Wechselnde Sorten täglich' },
    ],
    extrasCta: 'Tisch reservieren',
    hasMenu: true,
    hasPricelist: false,
    teamLabel: 'Wir sind das Café',
    aboutLabel: 'Unsere Philosophie',
    aboutDefault: 'Wir glauben, dass ein guter Kaffee mehr ist als ein Getränk. Er ist ein Moment der Stille, der Verbindung, des Genusses. Deshalb gehen wir bei jedem Schritt mit Liebe ans Werk.',
  },

  handwerk: {
    id: 'handwerk',
    label: 'Handwerk / Gewerbe',
    icon: '🔧',
    primaryColor: '#2b4590',
    accentColor: '#f5820d',
    bgColor: '#f4f7fb',
    textColor: '#1a2840',
    fontHeading: "'Oswald', Impact, sans-serif",
    fontBody: "'Open Sans', system-ui, sans-serif",
    googleFonts: 'Oswald:wght@400;600;700&family=Open+Sans:wght@300;400;600',
    defaultDark: false,
    defaultPhotos: [
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=1400&q=80&fit=crop',
    ],
    heroTagline: 'Qualität, die bleibt.',
    heroSubline: 'Ihr zuverlässiger Partner für [Gewerk] in [Stadt]',
    heroCta: 'Angebot anfordern',
    servicesLabel: 'Unsere Leistungen',
    servicesDefault: [
      { name: 'Beratung & Planung', price: 'Kostenlos', desc: 'Vor-Ort-Termin & Angebot' },
      { name: 'Montage & Installation', price: 'Nach Aufwand', desc: 'Fachgerechte Ausführung' },
      { name: 'Reparatur & Wartung', price: 'Ab 60 €/h', desc: 'Schnell & zuverlässig' },
      { name: 'Notfalldienst', price: '24/7', desc: 'Wir sind für Sie da' },
    ],
    extrasCta: 'Jetzt anrufen',
    hasMenu: false,
    hasPricelist: false,
    teamLabel: 'Unser Team',
    aboutLabel: 'Über uns',
    aboutDefault: 'Seit Jahren sind wir der verlässliche Partner für Handwerksleistungen in der Region. Qualität, Pünktlichkeit und Ehrlichkeit sind nicht nur Worte — das ist unsere Arbeitsweise.',
  },

  beauty: {
    id: 'beauty',
    label: 'Beauty & Wellness',
    icon: '💅',
    primaryColor: '#9b6b8a',
    accentColor: '#e8c4d4',
    bgColor: '#fdf9fb',
    textColor: '#2d1f28',
    fontHeading: "'Cormorant Garamond', Georgia, serif",
    fontBody: "'Nunito', system-ui, sans-serif",
    googleFonts: 'Cormorant+Garamond:wght@400;600;700&family=Nunito:wght@300;400;600',
    defaultDark: false,
    defaultPhotos: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=1400&q=80&fit=crop',
      'https://images.unsplash.com/photo-1571290274554-6a2eaa771e5f?w=1400&q=80&fit=crop',
    ],
    heroTagline: 'Schönheit ist Selbstfürsorge',
    heroSubline: 'Dein Wohlfühlort in [Stadt]',
    heroCta: 'Termin buchen',
    servicesLabel: 'Unsere Treatments',
    servicesDefault: [
      { name: 'Klassische Maniküre', price: '35 €', desc: 'Pflege & Lackierung nach Wahl' },
      { name: 'Gel-Nails', price: '55 €', desc: 'Langanhaltend & formschön' },
      { name: 'Gesichtsbehandlung', price: '70 €', desc: 'Reinigung, Peeling, Maske' },
      { name: 'Wimpernverlängerung', price: '90 €', desc: 'Voluminös & natürlich' },
    ],
    extrasCta: 'Online Termin buchen',
    hasMenu: false,
    hasPricelist: true,
    teamLabel: 'Unsere Expertinnen',
    aboutLabel: 'Willkommen bei uns',
    aboutDefault: 'Ein Ort, an dem du abschalten und dich um dich selbst kümmern kannst. Wir bieten professionelle Beauty-Treatments mit hochwertigen Produkten und einem Lächeln.',
    teamDefault: [
      { name: 'Elena Richter',  role: 'Beauty Expertin',    photoUrl: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=400&fit=crop&crop=faces' },
      { name: 'Laura Schmidt',  role: 'Kosmetikerin',       photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=faces' },
      { name: 'Mia Hoffmann',   role: 'Nail Art',           photoUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&crop=faces' },
      { name: 'Clara Vogel',    role: 'Masseurin & Wellness',photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=faces' },
    ],
  },
};

export const FONT_COMBOS = [
  { id: 'classic', label: 'Classic', heading: "'Playfair Display', Georgia, serif", body: "'Inter', system-ui, sans-serif", gfonts: 'Playfair+Display:wght@400;700&family=Inter:wght@300;400;500' },
  { id: 'bold', label: 'Bold', heading: "'Bebas Neue', Impact, sans-serif", body: "'Roboto', system-ui, sans-serif", gfonts: 'Bebas+Neue&family=Roboto:wght@300;400;700' },
  { id: 'editorial', label: 'Editorial', heading: "'Lora', Georgia, serif", body: "'Source Sans 3', system-ui, sans-serif", gfonts: 'Lora:wght@400;600;700&family=Source+Sans+3:wght@300;400;600' },
  { id: 'strong', label: 'Strong', heading: "'Oswald', Impact, sans-serif", body: "'Open Sans', system-ui, sans-serif", gfonts: 'Oswald:wght@400;600;700&family=Open+Sans:wght@300;400;600' },
  { id: 'elegant', label: 'Elegant', heading: "'Cormorant Garamond', Georgia, serif", body: "'Nunito', system-ui, sans-serif", gfonts: 'Cormorant+Garamond:wght@400;600;700&family=Nunito:wght@300;400;600' },
  { id: 'modern', label: 'Modern', heading: "'Syne', system-ui, sans-serif", body: "'DM Sans', system-ui, sans-serif", gfonts: 'Syne:wght@400;600;800&family=DM+Sans:wght@300;400;500' },
];
